paths:
  mph: "comsol/shoebox.mph"
  data: "data"

# --- Simulation configuration for COMSOL ---

room:
  dimensions:
    lx: 3.14 # width
    ly: 4.38 # depth
    lz: 3.27 # height
  center:
    x: 0
    y: 0
    z: room.dimensions.lz / 2 # place the room on the floor

sample:
  dimensions:
    lx: 1
    ly: 1
    lz: 0.05
  center:
    x: 0
    y: 0
    z: sample.dimensions.lz / 2 # place the sample on the floor

source:
  center:
    x: 0 
    y: 0 
    z: 1
  pressure: 1 # W

grid:
  domain_side: 1 # 1 m
  domain_height: 0.5 # 0.2 m
  dx: 0.025 # spatial resolution in x # 0.025 m
  dy: 0.025 # spatial resolution in y # 0.025 m
  dz: 0.01 # spatial resolution in z
  delta_height: 0.01 # distance between the sample and the grid
  x_start: -grid.domain_side / 2
  x_stop: grid.domain_side / 2
  y_start: -grid.domain_side / 2
  y_stop: grid.domain_side / 2
  z_start: sample.dimensions.lz + grid.delta_height
  z_stop: grid.z_start + grid.domain_height

mesh:
  num_elements_per_wavelength: 10

dataset:
  name: shoebox
  frequencies: [
      # 50,
      # 63,
      # 80,
      100,
      # 126,
      # 160,
      # 200,
      250,
      # # 320,
      # # 400,
      500,
      # # 630,
      # # 800,
      1000,
      # # 1270,
      # # 1600,
      2000,
      # 2500,
      # 3150, 
  ]

# --- Data processing configuration ---
downsampling: 2
nondim: 
  f: 
    shift: false
    scale: false
  x:
    shift: false
    scale: false
  y:
    shift: false
    scale: false
  z:
    shift: false
    scale: false
  p:
    shift: false
    scale: false