paths:
  mph: "C:\\Users\\STNj\\dtu\\thesis\\simulations\\.mph\\inf_baffle\\inf_baffle.mph"
  data: "C:\\Users\\STNj\\dtu\\thesis\\zpinn\\data"

# --- Simulation configuration for COMSOL ---
sample:
  dimensions:
    lx: 1
    ly: 1
    lz: 0.05
  center:
    x: 0
    y: 0
    z: sample.dimensions.lz / 2 # place the sample on the floor

source:
  center:
    x: 0 
    y: 0 
    z: 1
  pressure: 1 # W

grid:
  domain_side: 1 # 1 m
  domain_height: 0.01
  dx: 0.01 # spatial resolution in x
  dy: 0.01 # spatial resolution in y
  dz: 0.01 # spatial resolution in z
  delta_height: 0.01 # distance between the sample and the grid
  x_start: -grid.domain_side / 2
  x_stop: grid.domain_side / 2
  y_start: -grid.domain_side / 2
  y_stop: grid.domain_side / 2
  z_start: sample.dimensions.lz + grid.delta_height
  z_stop: grid.z_start + grid.domain_height

mesh:
  num_elements_per_wavelength: 6

dataset:
  name: inf_baffle
  frequencies: [
      # 50,
      # 63,
      # 80,
      # 100,
      # 126,
      # 160,
      # 200,
      250,
      # 320,
      # 400,
      # 500,
      # 630,
      # 800,
      # 1000,
      # 1270,
      # 1600,
      # 2000,
      # 2500,
      # 3150, 
  ]

# --- Data processing configuration ---
downsampling: 16
nondim: 
  f: 
    shift: false
    scale: true
  x:
    shift: true
    scale: true
  y:
    shift: true
    scale: true
  z:
    shift: false
    scale: true
  p:
    shift: true
    scale: true